### ISSUE TITLE
fritz-models style_transfer

### ISSUE THREAD

**Issue by tankfly2014** [fritzlabs/fritz-models#44]
When I use the generated image resolution to be 200*200, I can do BATCH =16, --alpha 0.3. Everything works fine.
But when my total resolution is 800*800 ('--image-size', default='800,800'), BATCH =1, --alpha 0.3, everything works. BATCH>1 will report an error.
This thing is so much memory card memory, my display card memory is 8GB, I hope BATCH can be higher. Is there any way I can optimize? For example, what parameters?

**Comment by jamesonthecrow** [comment]
Training the model requires much more memory than inference due because we must save intermediate layer outputs from the VGG model to extract style and content features for an image. Unfortunately, this means you will be unable to train a model using that high of an image size on your machine.

However, the image size you use for training is NOT the same as the image size you can use during inference. The model you train can be used to stylize images of ANY resolution during inference. The `--image-size` parameter set during training mostly impacts the relative size of the style textures during inference. For example, training a model at size 256x256 will produce smaller brush strokes with stylizing images during inference than a model training at 512x512.

**Comment by tankfly2014** [comment]
OK. I try it.
